apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-mutating-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-mutating-webhook
  template:
    metadata:
      labels:
        app: example-mutating-webhook
    spec:
      containers:
      - name: example-mutating-webhook
        image: dpluser/example-mutating-webhook:1.0.3-beta
        ports:
        - containerPort: 8443
        env:
        - name: TLS_KEY
          value: "/app/tls.key"
        - name: TLS_CRT
          value: "/app/tls.crt"
        volumeMounts:
          - mountPath: /app/tls.key
            name: tls-key
            subPath: tls.key
          - mountPath: /app/tls.crt
            name: tls-crt
            subPath: tls.crt
      volumes:
        - name: tls-key
          secret:
            secretName: example-mutating-webhook-tls
            defaultMode: 420
            items:
            - key: tls.key
              path: tls.key
        - name: tls-crt
          secret:
            secretName: example-mutating-webhook-tls
            defaultMode: 420
            items:
            - key: tls.crt
              path: tls.crt
